In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

bdd = pd.read_excel("Base_ER_FR.xlsx")

bdd.head()

,ID,AGE_CLI,B_MAT,B_RESMAT,CLASSACT,CSP,DARRET,E_EAD,E_OFF,E_ONB,MREVAU,MREVNU,MREVTOT,MTECH,NBIMP,NB_ECH,produit,RA,Tx,Unnamed: 19
0,a000001,53.0,NaN,NaN,1,42.0,201901,NaN,NaN,NaN,0.0,3216.0,3216.0,289.18,0,60,AMO,1302.91,2.309425,NaN
1,a000002,52.0,NaN,NaN,1,52.0,201901,NaN,NaN,NaN,0.0,2600.0,2600.0,340.98,0,60,AMO,4483.04,1.928135,NaN
2,a000003,53.0,NaN,NaN,1,45.0,201901,NaN,NaN,NaN,0.0,11000.0,11000.0,315.32,0,60,AMO,2468.04,2.377371,NaN
3,a000004,54.0,NaN,NaN,1,52.0,201901,NaN,NaN,NaN,0.0,1400.0,1400.0,384.46,0,60,AMO,4575.01,2.377371,NaN
4,a000005,27.0,NaN,NaN,1,47.0,201901,NaN,NaN,NaN,0.0,1515.0,1515.0,183.99,0,60,AMO,2360.23,1.927973,NaN

In [2]:
bdd.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ID           100000 non-null  str
 1   AGE_CLI      99524 non-null   float64
 2   B_MAT        98620 non-null   float64
 3   B_RESMAT     98620 non-null   float64
 4   CLASSACT     100000 non-null  int64
 5   CSP          97522 non-null   float64
 6   DARRET       100000 non-null  int64
 7   E_EAD        98620 non-null   float64
 8   E_OFF        98620 non-null   float64
 9   E_ONB        98620 non-null   float64
 10  MREVAU       99954 non-null   float64
 11  MREVNU       99954 non-null   float64
 12  MREVTOT      99954 non-null   float64
 13  MTECH        100000 non-null  float64
 14  NBIMP        100000 non-null  int64
 15  NB_ECH       100000 non-null  int64
 16  produit      100000 non-null  str
 17  RA           100000 non-null  float64
 18  Tx           95114 non-null   float64
 19  Unnamed: 19  0 non-null       float64
dtypes: float64(14), int64(4), str(2)
memory usage: 15.3 MB

In [3]:
bdd.describe(include="all")

,ID,AGE_CLI,B_MAT,B_RESMAT,CLASSACT,CSP,DARRET,E_EAD,E_OFF,E_ONB,MREVAU,MREVNU,MREVTOT,MTECH,NBIMP,NB_ECH,produit,RA,Tx,Unnamed: 19
count,100000,99524.000000,98620.000000,98620.00000,100000.00000,97522.000000,100000.00000,98620.00000,98620.0,98620.00000,99954.00000,99954.000000,99954.000000,100000.000000,100000.0000,100000.0000,100000,100000.000000,95114.000000,0.0
unique,100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN
top,a000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMO,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98404,NaN,NaN,NaN
mean,NaN,51.958472,70.807585,36.44999,1.00419,56.457968,202081.23258,998.00981,0.0,998.00981,96.15121,2433.213588,2529.364798,228.889002,0.0061,62.1022,NaN,8407.704481,2.104229,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
min,NaN,18.000000,0.000000,0.00000,1.00000,10.000000,201901.00000,0.00000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.0000,1.0000,NaN,-119694.120000,-1.500000,NaN
25%,NaN,40.000000,48.000000,7.00000,1.00000,47.000000,201912.00000,0.00000,0.0,0.00000,0.00000,1525.250000,1570.000000,94.670000,0.0000,36.0000,NaN,1688.965000,2.083425,NaN
50%,NaN,52.000000,61.000000,27.00000,1.00000,56.000000,202103.00000,0.00000,0.0,0.00000,0.00000,2000.000000,2057.000000,178.685000,0.0000,60.0000,NaN,4394.005000,2.177424,NaN
75%,NaN,64.000000,78.250000,50.00000,1.00000,70.000000,202205.00000,0.19000,0.0,0.19000,0.00000,2757.000000,2858.000000,296.970000,0.0000,72.0000,NaN,9638.880000,2.255798,NaN
max,NaN,92.000000,300.000000,298.00000,2.00000,90.000000,202312.00000,267563.81000,0.0,267563.81000,194096.00000,265000.000000,265000.000000,35915.740000,21.0000,300.0000,NaN,473016.880000,2.786456,NaN

In [8]:
bdd["CLASSACT"] = bdd["CLASSACT"].astype("category")

bdd["CLASSACT"].cat.categories

Index([1, 2], dtype='int64')

In [9]:
bdd["CLASSACT"].value_counts()

CLASSACT
1    99581
2      419
Name: count, dtype: int64

In [10]:
bdd["CSP"].value_counts(dropna=False)
bdd["CSP"] = bdd["CSP"].astype("category")
bdd["CSP"].cat.categories

Index([10.0, 21.0, 22.0, 23.0, 31.0, 32.0, 34.0, 35.0, 36.0, 37.0, 41.0, 42.0,
       43.0, 45.0, 46.0, 47.0, 48.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 60.0,
       61.0, 62.0, 64.0, 65.0, 66.0, 69.0, 70.0, 73.0, 76.0, 77.0, 78.0, 81.0,
       82.0, 84.0, 85.0, 87.0, 90.0],
      dtype='float64')

In [11]:
bdd["DARRET"] = pd.to_datetime(
    bdd["DARRET"].astype(str) + "01",
    format="%Y%m%d",
    errors="coerce"
)

bdd["DARRET"].head(10)
bdd["DARRET"].describe()

count      0
mean     NaT
min      NaT
25%      NaT
50%      NaT
75%      NaT
max      NaT
Name: DARRET, dtype: object

In [12]:
bdd["E_OFF"].describe()

count    98620.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: E_OFF, dtype: float64

In [13]:
bdd.drop(columns=["E_OFF"], inplace=True)
bdd.columns

Index(['ID', 'AGE_CLI', 'B_MAT', 'B_RESMAT', 'CLASSACT', 'CSP', 'DARRET',
       'E_EAD', 'E_ONB', 'MREVAU', 'MREVNU', 'MREVTOT', 'MTECH', 'NBIMP',
       'NB_ECH', 'produit', 'RA', 'Tx', 'Unnamed: 19'],
      dtype='str')

In [14]:
np.allclose(
    bdd["E_EAD"],
    bdd["E_ONB"],
    equal_nan=True
)
bdd.drop(columns=["E_ONB"], inplace=True)
bdd.columns

Index(['ID', 'AGE_CLI', 'B_MAT', 'B_RESMAT', 'CLASSACT', 'CSP', 'DARRET',
       'E_EAD', 'MREVAU', 'MREVNU', 'MREVTOT', 'MTECH', 'NBIMP', 'NB_ECH',
       'produit', 'RA', 'Tx', 'Unnamed: 19'],
      dtype='str')

In [15]:
(bdd["MREVTOT"] - (bdd["MREVNU"] + bdd["MREVAU"])).describe()
bdd.drop(columns=["MREVNU", "MREVAU"], inplace=True)
bdd.columns

Index(['ID', 'AGE_CLI', 'B_MAT', 'B_RESMAT', 'CLASSACT', 'CSP', 'DARRET',
       'E_EAD', 'MREVTOT', 'MTECH', 'NBIMP', 'NB_ECH', 'produit', 'RA', 'Tx',
       'Unnamed: 19'],
      dtype='str')

In [16]:
bdd["default"] = (bdd["NBIMP"] > 0).astype(int)
bdd["default"].value_counts()
bdd["default"].value_counts(normalize=True)

default
0    0.99553
1    0.00447
Name: proportion, dtype: float64

In [17]:
bdd["produit"].value_counts(dropna=False)
bdd["produit"] = bdd["produit"].astype("category")

cats = list(bdd["produit"].cat.categories)
if "AMO" in cats:
    cats.insert(0, cats.pop(cats.index("AMO")))
    bdd["produit"] = bdd["produit"].cat.reorder_categories(cats)

bdd["produit"].cat.categories

Index(['AMO', 'AR'], dtype='str')